site_name: Data Sharing In A Box Template by Dr. Danielle Boyce
site_url: https://boycelab.github.io/DataSharingInABox
repo_url: https://github.com/BoyceLab/DataSharingInABox
repo_name: BoyceLab/DataSharingInABox

theme:
  name: material
  logo: assets/img/IMG_7932.png
  favicon: assets/img/IMG_7932.png
  font:
    text: EB Garamond
  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

nav:
  - Home: index.md
  - How to Customize This Template: customization.md
  - Information for Researchers:
      - Overview: researchers.md
      - Cohort Overview: cohort-overview.md
      - Data Use Agreement: dua.md
      - End User Survey: survey.md
      - Sharing Platforms & Technologies: data-platforms.md
      - FAQ: faq.md
      - Data Dictionary: data-dictionary.md
      - Derived Fields: derived-fields.md
      - IRB Documentation: irb.md
  - Data Sharing Readiness: data-readiness.md
  - Key Resources:
      - Your Organization(s) Here: key_resources.md
      - NIH Data Sharing Language Explained: nih-data-sharing.md
      - PubMed: https://pubmed.ncbi.nlm.nih.gov/
      - ClinicalTrials.gov: https://clinicaltrials.gov/
      - NIH Sharing Policies: https://grants.nih.gov/policy-and-compliance/policy-topics/sharing-policies
      - FDA on Real-World Evidence: https://www.fda.gov/science-research/science-and-research-special-topics/real-world-evidence
      - EMA on Real-World Evidence: https://www.ema.europa.eu/en/about-us/how-we-work/data-regulation-big-data-other-sources/real-world-evidence
      - Acknowledgements: acknowledgements.md

markdown_extensions:
  - meta
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: false
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search

extra:
  generator: false
